---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-mariadb
  labels:
    app.kubernetes.io/name: oof-mariadb
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
---
# Source: mariadb/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: oof-mariadb
  namespace: oof-mariadb
  labels:
    app.kubernetes.io/instance: oof-mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.3.2
    helm.sh/chart: mariadb-0.16.7
type: Opaque
data:
  mariadb-root-password: 'bVd6clIzMFBKUTJNUGhxZEhJMk11WE5qMlA2QVpLZVQ='
---
# Source: mariadb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: oof-mariadb
  namespace: oof-mariadb
  labels:
    app.kubernetes.io/instance: oof-mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.3.2
    helm.sh/chart: mariadb-0.16.7
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app.kubernetes.io/instance: oof-mariadb
    app.kubernetes.io/name: mariadb
---
# Source: mariadb/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oof-mariadb
  namespace: oof-mariadb
  labels:
    app.kubernetes.io/instance: oof-mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.3.2
    helm.sh/chart: mariadb-0.16.7
spec:
  replicas: 1
  serviceName: oof-mariadb
  selector:
    matchLabels:
      app.kubernetes.io/instance: oof-mariadb
      app.kubernetes.io/name: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: oof-mariadb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/version: 12.3.2
        helm.sh/chart: mariadb-0.16.7
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 999
      initContainers:
      containers:
      - name: mariadb
        image: docker.io/mariadb:12.3.2@sha256:628f228f0fd5913a220438693576b29b6fe4dc1fa0a1298c0e98579fae28635f
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 999
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oof-mariadb
              key: mariadb-root-password
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - healthcheck.sh --connect --innodb_initialized
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - healthcheck.sh --connect --innodb_initialized
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir: {}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
      labels:
        app.kubernetes.io/instance: oof-mariadb
        app.kubernetes.io/name: mariadb
    spec:
      accessModes:
      - 'ReadWriteOnce'
      resources:
        requests:
          storage: '8Gi'
