apiVersion: orakel.ofunk.org/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: nginx-privileged
  namespace: oof-nginx-privileged
spec:
  targetRef:
    kind: Deployment
    name: nginx-privileged
  recordingDuration: 1m
  baselineRecordingReference: "oof-nginx-privileged:c5r289c6:baseline"
