apiVersion: orakel.ofunk.org/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: nginx-unprivileged
  namespace: oof-nginx-unprivileged
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-unprivileged
  recordingDuration: 1m
