# permissions for end users to edit workloadhardeningchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orakel-of-funk
    app.kubernetes.io/managed-by: kustomize
  name: workloadhardeningcheck-editor-role
rules:
- apiGroups:
  - orakel.ofunk.org
  resources:
  - workloadhardeningchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orakel.ofunk.org
  resources:
  - workloadhardeningchecks/status
  verbs:
  - get
