apiVersion: orakel.ofunk.org/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  labels:
    app.kubernetes.io/name: orakel-of-funk
  name: hello-node
  namespace: dev-workload
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-node
  baselineDuration: 1m
  suffix: blub
