---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-run-as-root
  labels:
    app.kubernetes.io/name: oof-run-as-root
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: run-as-root
  namespace: oof-run-as-root
  labels:
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
data:
  must_run_as_root: |
    #! /bin/bash
    set -e # Exit on error
    set -u # Treat unset variables as an error
    set -o pipefail # Fail on any command in a pipeline that fails

    while true
    do
      # This script checks if the user is root and exits with an error if not.
      if [ "$(id -u)" -ne 0 ]; then
        echo "[$( date --rfc-3339=s)] Error: This script must be run as root."
      else
        echo "[$( date --rfc-3339=s)] Running as root user."
      fi

      sleep 5 # Sleep for 5 seconds before checking again
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: root-check
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
  name: root-check
  namespace: oof-run-as-root
spec:
  selector:
    matchLabels:
      app: root-check
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: root-check
    spec:
      containers:
        - name: root-check
          image: docker.io/debian:bookworm
          command:
            - must_run_as_root
          securityContext: {}
          volumeMounts:
            - name: run-as-root-script
              mountPath: /usr/local/bin/must_run_as_root
              subPath: must_run_as_root
              readOnly: true
      volumes:
        - name: run-as-root-script
          configMap:
            name: run-as-root
            defaultMode: 0777
---
apiVersion: orakel.ofunk.org/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: root-check
  namespace: oof-run-as-root
  labels:
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root-check
  recordingDuration: 1m