---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-allow-priv-escalation
  labels:
    app.kubernetes.io/name: oof-allow-priv-escalation
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: try-privilege-escalation
  namespace: oof-allow-priv-escalation
  labels:
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
data:
  try_priv_escalation: |
    #! /bin/bash
    set -e # Exit on error
    set -u # Treat unset variables as an error
    set -o pipefail # Fail on any command in a pipeline that fails

    while true
    do
      if [[ $(setpriv -d | grep "no_new_privs: 1" | wc -l) -eq 1 ]]; then
          echo "[$( date --rfc-3339=s)] Error: Can't escalate privileges, no_new_privs is enabled."
      else
          echo "[$( date --rfc-3339=s)] Privilege escalation is possible."
      fi

      sleep 5 # Sleep for 5 seconds before checking again
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: allow-priv-escalation
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
  name: allow-priv-escalation
  namespace: oof-allow-priv-escalation
spec:
  selector:
    matchLabels:
      app: allow-priv-escalation
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: allow-priv-escalation
    spec:
      containers:
        - name: allow-priv-escalation
          image: docker.io/debian:bookworm
          command:
            - "try_priv_escalation"
          securityContext: {}
          volumeMounts:
            - name: try-privilege-escalation
              mountPath: /usr/local/bin/try_priv_escalation
              subPath: try_priv_escalation
              readOnly: true
      volumes:
        - name: try-privilege-escalation
          configMap:
            name: try-privilege-escalation
            defaultMode: 0777
---
apiVersion: orakel.ofunk.org/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: allow-priv-escalation
  namespace: oof-allow-priv-escalation
  labels:
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: allow-priv-escalation
  recordingDuration: 1m